# Generated by Django 6.0.2 on 2026-02-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblchat',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('senderID', models.IntegerField()),
                ('receiverID', models.IntegerField()),
                ('message', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tblClient',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('dob', models.DateField()),
                ('gender', models.TextField(max_length=10)),
                ('bloodGroup', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctor',
            fields=[
                ('doctdoctorIDorID', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.TextField(max_length=50)),
                ('displayContact', models.TextField(max_length=15)),
                ('bio', models.TextField(max_length=500)),
                ('displayAddress', models.TextField(max_length=100)),
                ('mode', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tblState',
            fields=[
                ('stateID', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblclientHistory',
            fields=[
                ('clientHistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('prescription', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('isMarkedSpecial', models.BooleanField(default=False)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
                ('docterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblAppointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('isAccepted', models.BooleanField(default=False)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblclient')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorImages',
            fields=[
                ('doctorImageID', models.AutoField(primary_key=True, serialize=False)),
                ('imageURL', models.ImageField(upload_to='doctor_images/')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblDoctorPost',
            fields=[
                ('docterPostID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('createDT', models.DateTimeField(auto_now_add=True)),
                ('docterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
            ],
        ),
        migrations.CreateModel(
            name='tblCity',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.TextField(max_length=50)),
                ('stateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblstate')),
            ],
        ),
        migrations.CreateModel(
            name='tblSubcategory',
            fields=[
                ('subcategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryName', models.TextField(max_length=50)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcategory')),
            ],
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='subcategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblsubcategory'),
        ),
        migrations.CreateModel(
            name='tblUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=10)),
                ('registrationDT', models.DateTimeField(auto_now_add=True)),
                ('profilePic', models.ImageField(upload_to='images/')),
                ('email', models.TextField(max_length=100)),
                ('mobileNumber', models.TextField(max_length=15)),
                ('IsDoctor', models.BooleanField(default=False)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcity')),
            ],
        ),
        migrations.CreateModel(
            name='tblReview',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
        migrations.CreateModel(
            name='tblnotification',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
        migrations.AddField(
            model_name='tbldoctor',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser'),
        ),
        migrations.CreateModel(
            name='tblComments',
            fields=[
                ('commentsID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
        ),
    ]
