# Generated by Django 6.0.2 on 2026-02-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldoctor',
            old_name='doctdoctorIDorID',
            new_name='doctorID',
        ),
    ]
