# Generated by Django 6.0.2 on 2026-03-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_doctdoctoridorid_tbldoctor_doctorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblclienthistory',
            old_name='docterID',
            new_name='doctorID',
        ),
        migrations.RenameField(
            model_name='tbldoctorpost',
            old_name='docterID',
            new_name='doctorID',
        ),
        migrations.RenameField(
            model_name='tbldoctorpost',
            old_name='docterPostID',
            new_name='doctorPostID',
        ),
    ]
