# Generated by Django 6.0.2 on 2026-03-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_docterid_tblclienthistory_doctorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblclient',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.tbluser'),
            preserve_default=False,
        ),
    ]
