# Generated by Django 6.0.2 on 2026-03-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tblclient_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcomments',
            name='doctorPostID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctorpost'),
            preserve_default=False,
        ),
    ]
