# Generated by Django 6.0.2 on 2026-03-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tblcomments_doctorpostid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblFollow',
            fields=[
                ('followID', models.AutoField(primary_key=True, serialize=False)),
                ('followedDT', models.DateTimeField(auto_now_add=True)),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbldoctor')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbluser')),
            ],
            options={
                'unique_together': {('userID', 'doctorID')},
            },
        ),
    ]
