# Generated by Django 6.0.2 on 2026-03-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tblfollow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblfollow',
            old_name='userID',
            new_name='followerUserID',
        ),
        migrations.AlterUniqueTogether(
            name='tblfollow',
            unique_together={('followerUserID', 'doctorID')},
        ),
    ]
