# Generated by Django 6.0.2 on 2026-03-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_userid_tblfollow_followeruserid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblfollow',
            old_name='followerUserID',
            new_name='userID',
        ),
        migrations.AlterUniqueTogether(
            name='tblfollow',
            unique_together={('userID', 'doctorID')},
        ),
    ]
