# Generated by Django 6.0.2 on 2026-03-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_followeruserid_tblfollow_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user.tblcomments'),
        ),
    ]
