# Generated by Django 6.0.2 on 2026-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tblcomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblappointment',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
